# Generated by Django 2.2.1 on 2020-11-16 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://s3.amazonaws.com/ODNUploads/532dfdbcc6479placeholder_food_item_2.png', max_length=500),
        ),
    ]
